name: Package & Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package linux-x64
        run: |
          dotnet publish ./src --runtime linux-x64 --self-contained -p:PublishSingleFile=true -c Release -o ./out/linux-x64
          cd ./out/linux-x64 && tar -czf ../deduplicator-linux-x64.tar.gz .
      - name: Package linux-arm64
        run: |
          dotnet publish ./src --runtime linux-arm64 --self-contained -p:PublishSingleFile=true -c Release -o ./out/linux-arm64
          cd ./out/linux-arm64 && tar -czf ../deduplicator-linux-arm64.tar.gz .
      - name: Package win-x64
        run: |
          dotnet publish ./src --runtime win-x64 --self-contained -p:PublishSingleFile=true -c Release -o ./out/win-x64
          cd ./out/win-x64 && zip -r ../deduplicator-win-x64.zip .
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEDUPLICATOR_RELEASES_PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload Asset deduplicator-linux-x64.tar.gz
        id: upload-release-asset-linux-x64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEDUPLICATOR_RELEASES_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./out/deduplicator-linux-x64.tar.gz
          asset_name: deduplicator-linux-x64.tar.gz
          asset_content_type: application/gzip
      - name: Upload Asset deduplicator-linux-arm64.tar.gz
        id: upload-release-asset-linux-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEDUPLICATOR_RELEASES_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./out/deduplicator-linux-arm64.tar.gz
          asset_name: deduplicator-linux-arm64.tar.gz
          asset_content_type: application/gzip
      - name: Upload Asset deduplicator-win-x64.zip
        id: upload-release-asset-win-x64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEDUPLICATOR_RELEASES_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./out/deduplicator-win-x64.zip
          asset_name: deduplicator-win-x64.zip
          asset_content_type: application/zip